export const GAME_FETCH = 'GAME_FETCH';
export const LETTER_GUESSED = 'LETTER_GUESSED';
export const LETTER_ERROR = 'LETTER_ERROR';
export const GAME_LOGIN_SUCCESS = 'GAME_LOGIN_SUCCESS';
export const GAME_LOGIN_REQUEST = 'GAME_LOGIN_REQUEST';
export const GAME_LOGOUT = 'GAME_LOGOUT;';